ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.2"
    hooks:
      - id: codespell
        args: ["-I", "codespell.txt"]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ["-l", "80"]
